// ─── User & Auth Tables ──────────────────────────────────────
export {
  roleEnum,
  userStatusEnum,
  users,
  roles,
  permissions,
  rolePermissions,
  refreshTokens,
  usersRelations,
  rolePermissionsRelations,
  refreshTokensRelations,
} from './users';

// ─── Academic Tables ─────────────────────────────────────────
export {
  attendanceStatusEnum,
  examTypeEnum,
  feeFrequencyEnum,
  feeStatusEnum,
  teachers,
  parents,
  classes,
  sections,
  students,
  subjects,
  teacherAssignments,
  timetables,
  attendance,
  assignments,
  assignmentSubmissions,
  exams,
  examSubjects,
  results,
  feeStructures,
  feeRecords,
  announcements,
  messages,
  auditLogs,
  parentsRelations,
  teachersRelations,
  studentsRelations,
  classesRelations,
  sectionsRelations,
  teacherAssignmentsRelations,
  timetablesRelations,
} from './academics';
